package com.yanchware.fractal.sdk.domain.entities.livesystem.caas.gcp;

public enum GcpZone {
  UsEast1B("us-east1-b"),
  UsEast1C("us-east1-c"),
  UsEast1D("us-east1-d"),
  UsEast4C("us-east4-c"),
  UsEast4B("us-east4-b"),
  UsEast4A("us-east4-a"),
  UsCentral1C("us-central1-c"),
  UsCentral1A("us-central1-a"),
  UsCentral1F("us-central1-f"),
  UsCentral1B("us-central1-b"),
  UsWest1B("us-west1-b"),
  UsWest1C("us-west1-c"),
  UsWest1A("us-west1-a"),
  EuWest4A("europe-west4-a"),
  EuWest4B("europe-west4-b"),
  EuWest4C("europe-west4-c"),
  EuWest1B("europe-west1-b"),
  EuWest1D("europe-west1-d"),
  EuWest1C("europe-west1-c"),
  EuWest3C("europe-west3-c"),
  EuWest3A("europe-west3-a"),
  EuWest3B("europe-west3-b"),
  EuWest2C("europe-west2-c"),
  EuWest2B("europe-west2-b"),
  EuWest2A("europe-west2-a"),
  AsiaEast1B("asia-east1-b"),
  AsiaEast1A("asia-east1-a"),
  AsiaEast1C("asia-east1-c"),
  AsiaSouthEast1B("asia-southeast1-b"),
  AsiaSouthEast1A("asia-southeast1-a"),
  AsiaSouthEast1C("asia-southeast1-c"),
  AsiaNorthEast1B("asia-northeast1-b"),
  AsiaNorthEast1C("asia-northeast1-c"),
  AsiaNorthEast1A("asia-northeast1-a"),
  AsiaSouth1C("asia-south1-c"),
  AsiaSouth1B("asia-south1-b"),
  AsiaSouth1A("asia-south1-a"),
  AustraliaSouthEast1B("australia-southeast1-b"),
  AustraliaSouthEast1C("australia-southeast1-c"),
  AustraliaSouthEast1A("australia-southeast1-a"),
  SouthAmericaEast1B("southamerica-east1-b"),
  SouthAmericaEast1C("southamerica-east1-c"),
  SouthAmericaEast1A("southamerica-east1-a"),
  AsiaEast2A("asia-east2-a"),
  AsiaEast2B("asia-east2-b"),
  AsiaEast2C("asia-east2-c"),
  AsiaNorthEast2A("asia-northeast2-a"),
  AsiaNorthEast2B("asia-northeast2-b"),
  AsiaNorthEast2C("asia-northeast2-c"),
  AsiaNorthEast3A("asia-northeast3-a"),
  AsiaNorthEast3B("asia-northeast3-b"),
  AsiaNorthEast3C("asia-northeast3-c"),
  AsiaSouth2A("asia-south2-a"),
  AsiaSouth2B("asia-south2-b"),
  AsiaSouth2C("asia-south2-c"),
  AsiaSouthEast2A("asia-southeast2-a"),
  AsiaSouthEast2B("asia-southeast2-b"),
  AsiaSouthEast2C("asia-southeast2-c"),
  AustraliaSouthEast2A("australia-southeast2-a"),
  AustraliaSouthEast2B("australia-southeast2-b"),
  AustraliaSouthEast2C("australia-southeast2-c"),
  EuCentral2A("europe-central2-a"),
  EuCentral2B("europe-central2-b"),
  EuCentral2C("europe-central2-c"),
  EuNorth1A("europe-north1-a"),
  EuNorth1B("europe-north1-b"),
  EuNorth1C("europe-north1-c"),
  EuWest6A("europe-west6-a"),
  EuWest6B("europe-west6-b"),
  EuWest6C("europe-west6-c"),
  NorthAmericaNorthEast1A("northamerica-northeast1-a"),
  NorthAmericaNorthEast1B("northamerica-northeast1-b"),
  NorthAmericaNorthEast1C("northamerica-northeast1-c"),
  NorthAmericaNorthEast2A("northamerica-northeast2-a"),
  NorthAmericaNorthEast2B("northamerica-northeast2-b"),
  NorthAmericaNorthEast2C("northamerica-northeast2-c"),
  UsWest2A("us-west2-a"),
  UsWest2B("us-west2-b"),
  UsWest2C("us-west2-c"),
  UsWest3A("us-west3-a"),
  UsWest3B("us-west3-b"),
  UsWest3C("us-west3-c"),
  UsWest4A("us-west4-a"),
  UsWest4B("us-west4-b"),
  UsWest4C("us-west4-c");

  private final String id;

  private GcpZone(final String id) {
    this.id = id;
  }

  public String id() {
    return id;
  }
}
