name: 'Master - PR Open'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  add_comment:
    if: github.event.action != 'synchronize'
    name: 'Add Comment'
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: Please set a versioning label of either `major`, `minor`, or `patch` to the pull request as it is required to be able to update pom version.
          repo-token: ${{ secrets.HalAccessToken }}